# This Action uses minimal steps to run in ~5 seconds to rapidly:
# look for typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://docs.astral.sh/ruff/
name: ci
on:
  push:
    # branches: [develop]
  pull_request:
    # branches: [develop]
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: codespell-project/actions-codespell@v2
      with:
        ignore_words_list: dout,maintainance,ser,tre
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
